#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../../../../detect-port@1.5.1/node_modules/detect-port/bin/detect-port.js" "$@"
else
  exec node  "$basedir/../../../../../detect-port@1.5.1/node_modules/detect-port/bin/detect-port.js" "$@"
fi
