#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../../../../@builder.io+partytown@0.7.6/node_modules/@builder.io/partytown/bin/partytown.cjs" "$@"
else
  exec node  "$basedir/../../../../../@builder.io+partytown@0.7.6/node_modules/@builder.io/partytown/bin/partytown.cjs" "$@"
fi
