#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../../../../create-gatsby@3.8.0/node_modules/create-gatsby/cli.js" "$@"
else
  exec node  "$basedir/../../../../../create-gatsby@3.8.0/node_modules/create-gatsby/cli.js" "$@"
fi
