#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../../../../node-gyp-build-optional-packages@5.0.7/node_modules/node-gyp-build-optional-packages/bin.js" "$@"
else
  exec node  "$basedir/../../../../../node-gyp-build-optional-packages@5.0.7/node_modules/node-gyp-build-optional-packages/bin.js" "$@"
fi
