#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../../../../autoprefixer@10.4.14_postcss@8.4.21/node_modules/autoprefixer/bin/autoprefixer" "$@"
else
  exec node  "$basedir/../../../../../autoprefixer@10.4.14_postcss@8.4.21/node_modules/autoprefixer/bin/autoprefixer" "$@"
fi
