#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../../../../eslint@7.32.0/node_modules/eslint/bin/eslint.js" "$@"
else
  exec node  "$basedir/../../../../../eslint@7.32.0/node_modules/eslint/bin/eslint.js" "$@"
fi
