#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../../../../envinfo@7.8.1/node_modules/envinfo/dist/cli.js" "$@"
else
  exec node  "$basedir/../../../../../envinfo@7.8.1/node_modules/envinfo/dist/cli.js" "$@"
fi
